-- AlterTable
ALTER TABLE `Dish` ADD COLUMN `imageUrl` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `Order` MODIFY `status` ENUM('PENDING', 'CONFIRMED', 'PAID', 'PREPARING', 'READY', 'DELIVERED', 'CANCELLED') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `Restaurant` ADD COLUMN `imageUrl` VARCHAR(191) NULL;
